#!/bin/sh

# Copyright © 2009-2016 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

if [ $# -ge 2 ]
then
    printf '%s [commit]\n' "$0" >&2
    exit 1
fi
if ! [ -d .git ]
then
    printf '%s requires git checkout\n' "$0" >&2
    exit 1
fi
set -e
pwd="$PWD"
commit=${1:-HEAD}
commit=$(git describe "$commit")
name=$(git cat-file blob "$commit:doc/changelog" | head -n1 | cut -d ' ' -f 1)
date=$(git rev-list -1 --format=%cI "$commit" | grep -o '^....-..-..' | tr -d -)
version=$(git cat-file blob "$commit:doc/changelog" | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(git cat-file blob "$commit:doc/changelog" | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Commit: %s\nVersion: %s\n' "$commit" "$version" >&2
set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export GZIP='-9 -n'
git archive "$commit" --prefix="$name-$version/" | tar -C "$sourceroot" -xf -
cd "$sourceroot"/*
rm .git*
rm .mailmap
rm .travis.yml
rm private/build-source-tarball
mv COPYING doc/
cd ..
tar -czf "$pwd/$name-$version.tar.gz" */
rm -r "$sourceroot"
set +x
cd "$pwd"
ls -d "$name-$version.tar.gz"

# vim:ts=4 sts=4 sw=4 et
