#!/bin/sh

# Copyright © 2009-2015 Jakub Wilk
#
# This package is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.

if [ $# -ge 2 ]
then
    printf '%s [revision]\n' "$0" >&2
    exit 1
fi
if ! [ -d .hg ]
then
    printf '%s requires hg checkout\n' "$0" >&2
    exit 1
fi
set -e
pwd="$PWD"
revision="${1:-tip}"
name=$(hg cat -r "$revision" doc/changelog | head -n1 | cut -d ' ' -f 1)
date=$(hg log -r "$revision" --template='{date|isodate}' | head -c 10 | tr -d -)
version=$(hg cat -r "$revision" doc/changelog | head -n1 | cut -d ' ' -f2 | tr -d '()')
released=$(hg cat -r "$revision" doc/changelog | head -n1 | grep -v -w UNRELEASED || true)
[ -n "$released" ] || version="${version}rc${date}"
printf 'Revision: %s\nVersion: %s\n' "$revision" "$version" >&2
set -x
sourceroot=$(mktemp -d -t "$name-source-XXXXXX")
export TAR_OPTIONS='--owner root --group root --mode a+rX --format ustar'
export GZIP='-9 -n'
hg archive -r "$revision" "$sourceroot/$name-$version"
cd "$sourceroot"/*
rm .hg*
rm .travis.yml
rm private/build-source-tarball
cd ..
tar -czf "$pwd/$name-$version.tar.gz" */
rm -r "$sourceroot"
set +x
cd "$pwd"
ls -d "$name-$version.tar.gz"

# vim:ts=4 sts=4 sw=4 et
