#!/bin/sh
version=${1:?"no version number provided"}
windows_version="$(printf -- '%s' "$version" | sed -e 's/[.]/,/g'),0"
set -e
set -x
dch -m -v "$version" -c doc/changelog
sed -i -r -e "s/<(!ENTITY version) '[0-9.]+'>/<\1 '$version'>/" doc/*.xml
